# Generated by Django 4.2.2 on 2023-06-22 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_subscriptions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='subscriptions',
            new_name='is_subscribed',
        ),
    ]
