# Generated by Django 4.2.2 on 2023-06-23 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_subscriber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_subscribed',
        ),
    ]
